# -*- coding: utf-8 -*-
"""Genera la propuesta GDA (5 secciones + encaje) en ES e EN para las 22 universidades."""
import os
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

ROOT = r"C:\Users\LENOVO\Documents\tesis-gda\06_Universidades"
ACT = os.path.join(ROOT, "Aplicaciones_Activas")
INT = os.path.join(ROOT, "Aplicaciones_Internacionales")

AUTOR = "Daniel Alejandro Pajoy Bastos"

TITULO_ES = ("Gobernanza digital asociativa: un modelo sociotécnico para la captura de valor en "
             "origen en organizaciones caficultoras de territorios PDET de Colombia")
TITULO_EN = ("Associative digital governance: a socio-technical model for value capture at origin "
             "in smallholder coffee organisations in Colombia's PDET territories")

PREGUNTA_ES = ("¿Cómo un modelo sociotécnico de gobernanza digital asociativa habilita a las "
               "organizaciones caficultoras de pequeña escala en territorios PDET de Colombia para "
               "incrementar la proporción de valor capturado en origen (VCO) en la cadena global de "
               "valor del café?")
PREGUNTA_EN = ("How does a socio-technical model of associative digital governance enable smallholder "
               "coffee organisations in Colombia's PDET territories to increase the share of value "
               "captured at origin (VCO) in the global coffee value chain?")

KW_ES = ("Gobernanza digital asociativa; Cadenas globales de valor; Captura de valor en origen; "
         "Acción colectiva; Soberanía de datos.")
KW_EN = ("Associative digital governance; Global value chains; Value capture at origin; "
         "Collective action; Data sovereignty.")

SEC2_ES = [
"Las organizaciones productoras de café en el Sur Global retienen apenas entre el 7 % y el 10 % del precio final al consumidor (Fitter & Kaplinsky, 2001; Talbot, 1997). Esta brecha no es una anomalía de mercado, sino el efecto de arquitecturas de gobernanza cautiva en las cadenas globales de valor (CGV), que concentran la captura de renta en los eslabones de torrefacción y distribución y transfieren los riesgos climáticos y de precio hacia la base productora (Gereffi et al., 2005; Grabs & Ponte, 2019). El problema central de esta investigación es, por tanto, la baja proporción de valor capturado en origen (VCO): la fracción del valor de la cadena que las organizaciones caficultoras logran retener en el territorio.",
"En Colombia, este problema se agudiza en los territorios de los Programas de Desarrollo con Enfoque Territorial (PDET), política de implementación del Acuerdo de Paz de 2016 que abarca 170 municipios, 16 subregiones y más de seis millones de personas en zonas de alta vulnerabilidad histórica (Decreto 893/2017). Allí, las organizaciones caficultoras de pequeña escala enfrentan cuatro déficits estructurales que, combinados, bloquean cualquier incremento sostenible del VCO: (i) déficits de gobernanza organizacional heredados del conflicto armado (Ostrom, 1990; Rettberg, 2010); (ii) posicionamiento cautivo en la CGV (Gereffi et al., 2005; Hornborg, 2016); (iii) exclusión digital que amenaza el cumplimiento del Reglamento de Deforestación de la Unión Europea (EUDR, Reglamento 2023/1115), vigente para el café desde 2026; y (iv) exclusión de las arquitecturas de financiamiento y trazabilidad que podrían reposicionarlas en la cadena. Estos déficits se retroalimentan y reproducen la posición periférica del productor colombiano en el sistema-mundo del café (Wallerstein, 1974): los instrumentos parciales —tecnología sin gobernanza colectiva, certificación sin poder de negociación, financiamiento sin trazabilidad— no se traducen en retención de renta.",
"La literatura sobre CGV describe con precisión los mecanismos de extracción de renta, pero no especifica las condiciones de gobernanza bajo las cuales las organizaciones de pequeños productores pueden reposicionarse para incrementar su VCO (Gereffi et al., 2005; Grabs & Ponte, 2019). La teoría ostromiana de la acción colectiva establece los principios institucionales para la gobernanza sostenible de los comunes, pero no incorpora ni la mediación digital ni los contextos de posconflicto de baja madurez institucional (Ostrom, 1990; Agrawal, 2001). La literatura emergente sobre gobernanza digital y registros distribuidos explora la reducción de asimetrías de información, pero no la articula con la gobernanza institucional colectiva en territorios de alta fragilidad (Werbach, 2018). Persiste así un vacío: ningún modelo integra la gobernanza asociativa, la arquitectura sociotécnica y la medición del valor retenido en un constructo aplicable a organizaciones caficultoras de pequeña escala en posconflicto.",
"Esta investigación responde a ese vacío mediante un modelo sociotécnico de Gobernanza Digital Asociativa (GDA): un constructo en el que la gobernanza institucional colectiva (subsistema social) y una arquitectura digital de confianza —trazabilidad y soberanía de datos— (subsistema técnico) se optimizan conjuntamente —el principio nuclear de la teoría sociotécnica (Abbas & Michael, 2026), cuyo origen (Trist & Bamforth, 1951) conserva plena vigencia analítica en la era de la Industria 4.0 (Horváth & Kemser, 2026)— para habilitar el incremento del VCO. La contribución esperada es triple: teórica —un modelo integrador de gobernanza digital-institucional para el posconflicto agroalimentario—; metodológica —un protocolo de Design Science Research mixto y secuencial, replicable en otros contextos del Sur Global—; y praxeológica —artefactos directamente implementables por las organizaciones y escalables a otras cadenas agroalimentarias—. El proyecto es viable en cuatro años (2026–2029) y cuenta con acceso directo al campo a través de la Federación Mesa Nacional del Café, que agremia a las asociaciones caficultoras firmantes de paz.",
]

SEC2_EN = [
"Coffee-producing organisations in the Global South retain barely 7–10% of the final consumer price (Fitter & Kaplinsky, 2001; Talbot, 1997). This gap is not a market anomaly but the effect of captive governance architectures in global value chains (GVCs), which concentrate rent capture in the roasting and distribution links and transfer climatic and price risks onto the producer base (Gereffi et al., 2005; Grabs & Ponte, 2019). The central problem of this research is therefore the low share of value captured at origin (VCO): the fraction of chain value that coffee organisations manage to retain in the territory.",
"In Colombia, this problem is most acute in the territories of the Development Programmes with a Territorial Focus (PDET), the policy implementing the 2016 Peace Agreement, covering 170 municipalities, 16 subregions and more than six million people in areas of high historical vulnerability (Decree 893/2017). There, smallholder coffee organisations face four structural deficits that, combined, block any sustainable increase in VCO: (i) organisational governance deficits inherited from the armed conflict (Ostrom, 1990; Rettberg, 2010); (ii) captive positioning in the GVC (Gereffi et al., 2005; Hornborg, 2016); (iii) digital exclusion that threatens compliance with the European Union Deforestation Regulation (EUDR, Regulation 2023/1115), in force for coffee since 2026; and (iv) exclusion from the financing and traceability architectures that could reposition them in the chain. These deficits reinforce one another and reproduce the peripheral position of the Colombian producer in the world coffee system (Wallerstein, 1974): partial instruments —technology without collective governance, certification without bargaining power, financing without traceability— do not translate into rent retention.",
"The GVC literature describes rent-extraction mechanisms with precision but does not specify the governance conditions under which smallholder organisations can reposition themselves to increase their VCO (Gereffi et al., 2005; Grabs & Ponte, 2019). Ostromian collective-action theory establishes the institutional principles for the sustainable governance of the commons but incorporates neither digital mediation nor post-conflict contexts of low institutional maturity (Ostrom, 1990; Agrawal, 2001). The emerging literature on digital governance and distributed ledgers explores the reduction of information asymmetries but does not articulate it with collective institutional governance in highly fragile territories (Werbach, 2018). A gap thus persists: no model integrates associative governance, socio-technical architecture and the measurement of retained value into a construct applicable to smallholder coffee organisations in post-conflict settings.",
"This research addresses that gap through a socio-technical model of Associative Digital Governance (ADG): a construct in which collective institutional governance (social subsystem) and a digital architecture of trust —traceability and data sovereignty— (technical subsystem) are jointly optimised —the core principle of socio-technical theory (Abbas & Michael, 2026), whose origin (Trist & Bamforth, 1951) retains full analytical relevance in the age of Industry 4.0 (Horváth & Kemser, 2026)— to enable the increase of VCO. The expected contribution is threefold: theoretical —an integrative model of digital-institutional governance for the agri-food post-conflict—; methodological —a sequential mixed-methods Design Science Research protocol, replicable in other Global South contexts—; and praxeological —artefacts directly implementable by the organisations and scalable to other agri-food chains—. The project is feasible within four years (2026–2029) and has direct field access through the National Coffee Roundtable Federation (FEMNCAFE), which brings together the associations of peace-signatory coffee growers.",
]

SEC3_ES = [
"Las cadenas globales de valor (CGV) constituyen el marco analítico central de esta investigación: determinan quién define los estándares de calidad y sostenibilidad, quién fija los precios de referencia y, en última instancia, quién retiene la renta generada a lo largo de la cadena (Gereffi et al., 2005). En las cadenas cautivas que caracterizan al café convencional colombiano, los compradores internacionales ejercen un poder estructural que Wallerstein (1974) denominó intercambio desigual y que Grabs y Ponte (2019) mostraron reproducido, paradójicamente, por los propios estándares privados de sostenibilidad. La teoría del upgrading (Humphrey & Schmitz, 2002) identifica trayectorias de mejora de posición cuya activación exige una combinación de capacidades organizacionales, acceso tecnológico y vínculos institucionales que las organizaciones caficultoras en posconflicto raramente poseen de manera simultánea. El marco de las redes de producción global (GPN 2.0) (Yeung & Coe, 2015) completa el encuadre al incorporar los actores no empresariales —Estado, sociedad civil y cooperación internacional— que configuran las condiciones territoriales del posconflicto y resultan invisibles en la tipología clásica de CGV.",
"La tradición de la gobernanza de los comunes (Ostrom, 1990) ofrece el marco más robusto para entender las condiciones bajo las cuales las organizaciones de pequeños productores gestionan recursos colectivos de manera sostenible. Sus ocho principios de diseño institucional han sido validados en múltiples contextos agroalimentarios (Agrawal, 2001) y constituyen la base empírica para construir indicadores de gobernanza colectiva. Sin embargo, su extensión a entornos posconflicto —donde el capital social fue sistemáticamente destruido por el conflicto armado (Rettberg, 2010) y los fallos de gobernanza cooperativa son estructurales (Ortmann & King, 2007)— exige adaptar los principios originales a condiciones de alta fragilidad institucional. La investigación-acción participativa (Fals Borda, 1986) aporta el fundamento epistemológico: el conocimiento sobre la gobernanza territorial posconflicto debe co-construirse con las comunidades, no imponerse desde marcos diseñados en contextos de alta madurez institucional.",
"El puente entre la gobernanza colectiva y la dimensión digital lo provee la teoría sociotécnica, que conceptualiza todo sistema de trabajo como la articulación de un subsistema social y uno técnico cuyo desempeño depende de su optimización conjunta (Abbas & Michael, 2026). Originada en los estudios del Instituto Tavistock sobre la mecanización minera (Trist & Bamforth, 1951) y desarrollada hacia el análisis de entornos organizacionales complejos (Emery & Trist, 1965; Trist, 1981), esta tradición demuestra que la introducción de tecnología que ignora el subsistema social degrada el desempeño del conjunto —un principio cuya vigencia se reafirma en la era de la Industria 4.0 (Horváth & Kemser, 2026). Para esta investigación, ello implica que ninguna arquitectura digital puede incrementar el VCO si no se diseña conjuntamente con la gobernanza asociativa que la opera.",
"Sobre esa base, la gobernanza digital y los registros distribuidos emergen como mecanismos con potencial transformador para las cadenas agroalimentarias: reducen asimetrías de información, habilitan trazabilidad georreferenciada verificable —condición técnica del EUDR— y pueden automatizar la distribución de beneficios dentro de las organizaciones (Werbach, 2018; Elmatsani et al., 2026). No obstante, estos mecanismos solo producen retención de renta territorial cuando operan sobre una base de gobernanza colectiva sólida (Cong et al., 2020; Schletz et al., 2023): la tecnología sin gobernanza reproduce y amplifica las asimetrías de poder existentes. De la articulación de estas cuatro tradiciones —CGV, gobernanza de los comunes, teoría sociotécnica y gobernanza digital— surge el constructo de Gobernanza Digital Asociativa (GDA), que especifica las condiciones de gobernanza bajo las cuales un subsistema social asociativo y un subsistema técnico digital, optimizados conjuntamente, habilitan a las organizaciones caficultoras de pequeña escala para incrementar su valor capturado en origen.",
]

SEC3_EN = [
"Global value chains (GVCs) constitute the central analytical framework of this research: they determine who sets quality and sustainability standards, who fixes reference prices and, ultimately, who retains the rent generated along the chain (Gereffi et al., 2005). In the captive chains that characterise conventional Colombian coffee, international buyers exert a structural power that Wallerstein (1974) termed unequal exchange and that Grabs and Ponte (2019) showed to be reproduced, paradoxically, by private sustainability standards themselves. Upgrading theory (Humphrey & Schmitz, 2002) identifies trajectories for improving position whose activation requires a combination of organisational capabilities, technological access and institutional links that post-conflict coffee organisations rarely possess simultaneously. The global production networks framework (GPN 2.0) (Yeung & Coe, 2015) completes the framing by incorporating the non-firm actors —State, civil society and international cooperation— that shape the territorial conditions of the post-conflict and remain invisible in the classic GVC typology.",
"The tradition of the governance of the commons (Ostrom, 1990) offers the most robust framework for understanding the conditions under which smallholder organisations sustainably manage collective resources. Its eight institutional design principles have been validated in multiple agri-food contexts (Agrawal, 2001) and provide the empirical basis for constructing collective-governance indicators. However, extending this framework to post-conflict settings —where social capital was systematically destroyed by the armed conflict (Rettberg, 2010) and cooperative governance failures are structural (Ortmann & King, 2007)— requires adapting the original principles to conditions of high institutional fragility. Participatory action research (Fals Borda, 1986) provides the epistemological foundation: knowledge about post-conflict territorial governance must be co-constructed with communities, not imposed from frameworks designed in contexts of high institutional maturity.",
"The bridge between collective governance and the digital dimension is provided by socio-technical theory, which conceptualises every work system as the articulation of a social and a technical subsystem whose performance depends on their joint optimisation (Abbas & Michael, 2026). Originating in the Tavistock Institute studies on the mechanisation of mining (Trist & Bamforth, 1951) and developed towards the analysis of complex organisational environments (Emery & Trist, 1965; Trist, 1981), this tradition demonstrates that introducing technology that ignores the social subsystem degrades the performance of the whole —a principle whose relevance is reaffirmed in the age of Industry 4.0 (Horváth & Kemser, 2026). For this research, this implies that no digital architecture can increase VCO unless it is designed jointly with the associative governance that operates it.",
"On this basis, digital governance and distributed ledgers emerge as mechanisms with transformative potential for agri-food chains: they reduce information asymmetries, enable verifiable geo-referenced traceability —a technical condition of the EUDR— and can automate the distribution of benefits within organisations (Werbach, 2018; Elmatsani et al., 2026). Nevertheless, these mechanisms only produce territorial rent retention when they operate on a solid base of collective governance (Cong et al., 2020; Schletz et al., 2023): technology without governance reproduces and amplifies existing power asymmetries. From the articulation of these four traditions —GVCs, governance of the commons, socio-technical theory and digital governance— emerges the construct of Associative Digital Governance (ADG), which specifies the governance conditions under which an associative social subsystem and a digital technical subsystem, jointly optimised, enable smallholder coffee organisations to increase their value captured at origin.",
]

SEC4_ES = [
"La investigación adopta el paradigma de Design Science Research (DSR) (Hevner et al., 2004), que combina el rigor empírico de la investigación científica con la relevancia práctica del diseño de artefactos implementables. El enfoque es mixto secuencial: el diagnóstico cualitativo de la Fase I calibra el diseño del modelo en la Fase II, y el consenso experto de la Fase II provee las distribuciones de entrada de la simulación estocástica de la Fase III.",
"La Fase I — Diagnóstica establece la línea base del Valor Capturado en Origen (VCO₀): la proporción del precio final que retiene hoy la organización en la cadena global de valor. Combina entrevistas semiestructuradas con líderes de organizaciones caficultoras, análisis de redes sociales (SNA) para mapear el capital social posconflicto, y mapeo de la CGV para cuantificar la distribución actual del valor a lo largo de la cadena del café colombiano. En paralelo, se construye el Índice de Consolidación PDET (IPDET) —que integra consolidación institucional, condiciones de seguridad e implementación del Acuerdo de Paz— como variable moderadora que permite extrapolar el efecto del modelo desde el caso de validación hacia los distintos contextos de los territorios PDET del país.",
"La Fase II — Constructiva diseña, prototipa e itera los mecanismos del modelo GDA mediante talleres de diseño participativo con las comunidades caficultoras y un panel Delphi de validación de consenso. El Delphi no solo valida el diseño: sus rangos de estimación sobre el Índice de Gobernanza (IG), el componente tecnológico y el comportamiento del IPDET constituyen las distribuciones a priori que alimentan la simulación de la Fase III.",
"La Fase III — Evaluativa cuantifica el efecto del modelo sobre el VCO y prueba la hipótesis central mediante una simulación de Monte Carlo de al menos 10.000 iteraciones con índices de sensibilidad de Sobol. La pregunta evaluativa principal es: ¿qué subsistema contribuye más a la varianza del VCO, el bloque de gobernanza (IG) o el bloque tecnológico? Los índices de Sobol descomponen la varianza total del VCO en la contribución de cada variable, permitiendo una evaluación empírica de la hipótesis central —la gobernanza explica más varianza que la tecnología en la captura de valor en origen—. Como prueba de robustez, un análisis de escenarios adversos (pruebas de estrés) —caída de precios, deterioro de seguridad, fallo institucional— verifica si el incremento del VCO se sostiene bajo condiciones de estrés y resulta generalizable más allá del escenario base. Un estudio de caso embebido longitudinal en organizaciones piloto de territorios PDET y una encuesta a la red FEMNCAFE completan la validación empírica y de transferibilidad. El diseño ético incluye aprobación del comité de ética institucional, protocolos de consentimiento informado adaptados al contexto cultural y de seguridad de los territorios PDET, y mecanismos de soberanía de datos de la trazabilidad digital.",
]

SEC4_EN = [
"This research adopts the Design Science Research (DSR) paradigm (Hevner et al., 2004), which combines the empirical rigour of scientific research with the practical relevance of designing implementable artefacts. The approach is sequential mixed-methods: the qualitative diagnosis of Phase I calibrates the model design in Phase II, and the expert consensus of Phase II provides the input distributions for the stochastic simulation of Phase III.",
"Phase I — Diagnostic establishes the baseline Value Captured at Origin (VCO₀): the share of the final price that the organisation currently retains in the global value chain. It combines semi-structured interviews with leaders of coffee organisations, social network analysis (SNA) to map post-conflict social capital, and GVC mapping to quantify the current distribution of value along the Colombian coffee chain. In parallel, the PDET Consolidation Index (IPDET) —integrating institutional consolidation, security conditions and Peace Agreement implementation— is constructed as a moderating variable that allows the model's effect to be extrapolated from the validation case to the diverse contexts of the country's PDET territories.",
"Phase II — Constructive designs, prototypes and iterates the ADG model's mechanisms through participatory design workshops with coffee communities and a Delphi consensus-validation panel. The Delphi does not merely validate the design: its estimation ranges for the Governance Index (IG), the technological component and the behaviour of the IPDET constitute the prior distributions that feed the Phase III simulation.",
"Phase III — Evaluative quantifies the model's effect on VCO and tests the central hypothesis through a Monte Carlo simulation of at least 10,000 iterations with Sobol sensitivity indices. The main evaluative question is: which subsystem contributes most to VCO variance, the governance block (IG) or the technological block? Sobol indices decompose the total VCO variance into the contribution of each variable, enabling an empirical evaluation of the central hypothesis —governance explains more variance than technology in value capture at origin—. As a robustness test, an adverse-scenario analysis (stress testing) —price collapse, security deterioration, institutional failure— verifies whether the VCO increase holds under stress conditions and is generalisable beyond the baseline scenario. A longitudinal embedded case study in pilot organisations in PDET territories and a survey of the FEMNCAFE network complete the empirical and transferability validation. The ethical design includes institutional ethics-committee approval, informed-consent protocols adapted to the cultural and security context of PDET territories, and data-sovereignty mechanisms for the digital traceability.",
]

REFS_CORE = [
"Abbas, R., & Michael, K. (2026). Socio-technical theory: A review. En S. Papagiannidis (Ed.), TheoryHub book. https://open.ncl.ac.uk (ISBN 9781739604400)",
"Agrawal, A. (2001). Common property institutions and sustainable governance of resources. World Development, 29(10), 1649–1672. https://doi.org/10.1016/S0305-750X(01)00063-8",
"Cong, L. W., Li, Y., & Wang, N. (2020). Tokenomics: Dynamic adoption and valuation. The Review of Financial Studies, 34(3), 1105–1155. https://doi.org/10.1093/rfs/hhaa089",
"Elmatsani, H. M., et al. (2026). Bridging the governance gap in agricultural blockchain-based smart contracts. Frontiers in Blockchain. https://doi.org/10.3389/fbloc.2026.1762861",
"Emery, F. E., & Trist, E. L. (1965). The causal texture of organizational environments. Human Relations, 18(1), 21–32. https://doi.org/10.1177/001872676501800103",
"Fals Borda, O. (1986). Conocimiento y poder popular. Siglo XXI Editores.",
"Fitter, R., & Kaplinsky, R. (2001). Who gains from product rents as the coffee market becomes more differentiated? IDS Bulletin, 32(3), 69–82. https://doi.org/10.1111/j.1759-5436.2001.mp32003008.x",
"Gereffi, G., Humphrey, J., & Sturgeon, T. (2005). The governance of global value chains. Review of International Political Economy, 12(1), 78–104. https://doi.org/10.1080/09692290500049805",
"Grabs, J., & Ponte, S. (2019). The evolution of power in the global coffee value chain and production network. Journal of Economic Geography, 19(4), 803–828. https://doi.org/10.1093/jeg/lbz008",
"Hevner, A. R., March, S. T., Park, J., & Ram, S. (2004). Design science in information systems research. MIS Quarterly, 28(1), 75–105. https://doi.org/10.2307/25148625",
"Hornborg, A. (2016). Global magic: Technologies of appropriation from ancient Rome to Wall Street. Palgrave Macmillan.",
"Horváth, A., & Kemser, H.-P. (2026). Human, organisation and social system in the intelligent factory: The contemporary relevance of socio-technical systems theory in the age of Industry 4.0. International Review of Applied Sciences and Engineering. https://doi.org/10.1556/1848.2026.01263",
"Humphrey, J., & Schmitz, H. (2002). How does insertion in global value chains affect upgrading in industrial clusters? Regional Studies, 36(9), 1017–1027. https://doi.org/10.1080/0034340022000022198",
"Ortmann, G. F., & King, R. P. (2007). Agricultural cooperatives I: History, theory and problems. Agrekon, 46(1), 18–46. https://doi.org/10.1080/03031853.2007.9523760",
"Ostrom, E. (1990). Governing the commons: The evolution of institutions for collective action. Cambridge University Press.",
"Parlamento Europeo y Consejo de la Unión Europea. (2023). Reglamento (UE) 2023/1115 relativo a la comercialización de determinadas materias primas y productos asociados a la deforestación. Diario Oficial de la Unión Europea. https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=CELEX%3A32023R1115",
"Presidencia de la República de Colombia. (2017). Decreto 893 de 2017. Diario Oficial No. 50.230.",
"Rettberg, A. (2010). Global markets, local conflict: Violence in the Colombian coffee region after the breakdown of the International Coffee Agreement. Latin American Perspectives, 37(2), 111–132. https://doi.org/10.1177/0094582x09356961",
"Schletz, M., et al. (2023). Blockchain and regenerative finance: Charting a path toward regeneration. Frontiers in Blockchain, 6, Article 1165133. https://doi.org/10.3389/fbloc.2023.1165133",
"Talbot, J. M. (1997). Where does your coffee dollar go? The division of income and surplus along the coffee commodity chain. Studies in Comparative International Development, 32(1), 56–91. https://doi.org/10.1007/bf02696306",
"Trist, E. L. (1981). The evolution of socio-technical systems: A conceptual framework and an action research program (Occasional Paper No. 2). Ontario Quality of Working Life Centre.",
"Trist, E. L., & Bamforth, K. W. (1951). Some social and psychological consequences of the longwall method of coal-getting. Human Relations, 4(1), 3–38. https://doi.org/10.1177/001872675100400101",
"Wallerstein, I. (1974). The modern world-system I: Capitalist agriculture and the origins of the European world-economy in the sixteenth century. Academic Press.",
"Werbach, K. (2018). The blockchain and the new architecture of trust. MIT Press.",
"Yeung, H. W.-C., & Coe, N. M. (2015). Toward a dynamic theory of global production networks. Economic Geography, 91(1), 29–58. https://doi.org/10.1111/ecge.12063",
]

REFS_UPM_EXTRA = [
"Benito-Hernández, S., López-Cózar-Navarro, C., & Priede-Bergamini, T. (2023). The influence of government support over environmental protection investment on SMEs. Business Ethics, the Environment & Responsibility, 32, 836–846. https://doi.org/10.1111/beer.12496",
"Merbah, N., & Benito-Hernández, S. (2023). Sustainability labels in the Spanish coffee market: A hedonic price approach. Spanish Journal of Agricultural Research, 21(1), e0102. https://doi.org/10.5424/sjar/2023211-19510",
]

# ---- Encajes: clave -> (es, en) ----
ENC = {
"UPM": ("Esta investigación se inscribe en las líneas de Economía Agraria y Recursos Naturales y de Gestión Empresarial e Innovación del programa TAPAS, bajo la dirección de la Dra. Sonia Benito Hernández. Su investigación sobre el valor implícito de las etiquetas de sostenibilidad en el mercado español del café (Merbah & Benito-Hernández, 2023) cuantifica la prima que el mercado de consumo reconoce a los atributos de sostenibilidad; esta investigación cierra el circuito analítico al examinar los mecanismos de gobernanza que habilitan a las organizaciones caficultoras para capturar en origen ese valor.",
        "This research is situated within the Agricultural Economics and Natural Resources line and the Business Management and Innovation line of the TAPAS programme, under the supervision of Dr. Sonia Benito Hernández. Her work on the implicit value of sustainability labels in the Spanish coffee market (Merbah & Benito-Hernández, 2023) quantifies the premium that the consumer market grants to sustainability attributes; this research closes the analytical loop by examining the governance mechanisms that enable coffee organisations to capture that value at origin."),
"Deusto": ("Esta investigación se inscribe en el programa CETIS y en la agenda de competitividad territorial e innovación regional del Instituto Orkestra (Wilson, Magro): el constructo GDA opera como un mecanismo de upgrading en cadenas globales que reposiciona competitivamente a los territorios productores, traduciendo capacidades de gobernanza colectiva en retención de valor (VCO) y diferenciación regional sostenible.",
           "This research is situated within the CETIS programme and the territorial competitiveness and regional innovation agenda of the Orkestra Institute (Wilson, Magro): the ADG construct operates as an upgrading mechanism in global chains that competitively repositions producer territories, translating collective-governance capabilities into value retention (VCO) and sustainable regional differentiation."),
"Loyola": ("Esta investigación se inscribe en el programa de Desarrollo Inclusivo y Sostenible y su compromiso con los ODS y la economía solidaria: la GDA aborda directamente la justicia distributiva en cadenas agroalimentarias del Sur Global, situando a las organizaciones caficultoras de territorios PDET posconflicto como sujetos de un desarrollo que retiene valor, conocimiento y soberanía de datos en origen.",
           "This research is situated within the Inclusive and Sustainable Development programme and its commitment to the SDGs and the solidarity economy: ADG directly addresses distributive justice in Global South agri-food chains, positioning smallholder coffee organisations in post-conflict PDET territories as subjects of a development that retains value, knowledge and data sovereignty at origin."),
"Mondragon": ("Esta investigación dialoga con la tradición de economía social y gobernanza cooperativa democrática que define a Mondragón: el subsistema social de la GDA se fundamenta en los principios ostromianos de acción colectiva y autogobierno, y examina cómo las organizaciones asociativas caficultoras pueden gobernar democráticamente una infraestructura digital común para capturar valor en origen.",
              "This research engages the tradition of social economy and democratic cooperative governance that defines Mondragón: the social subsystem of ADG is grounded in Ostromian principles of collective action and self-governance, examining how associative coffee organisations can democratically govern a shared digital infrastructure to capture value at origin."),
"UAB": ("Esta investigación se inscribe en la tradición de sociología económica y estudios de ciencia y tecnología (STS): la GDA se construye sobre el principio sociotécnico de optimización conjunta (Trist & Bamforth, 1951; Abbas & Michael, 2026), analizando la coproducción de lo social y lo digital en la gobernanza de cadenas globales y la distribución territorial del valor.",
        "This research is situated within the tradition of economic sociology and science and technology studies (STS): ADG is built on the socio-technical principle of joint optimisation (Trist & Bamforth, 1951; Abbas & Michael, 2026), analysing the co-production of the social and the digital in the governance of global chains and the territorial distribution of value."),
"UPV": ("Esta investigación se inscribe en la línea de digitalización de cadenas agroalimentarias: el subsistema técnico de la GDA —trazabilidad inmutable, IoT y cumplimiento del EUDR— se diseña conjuntamente con la gobernanza asociativa que lo opera, demostrando que la arquitectura digital solo produce retención de valor cuando se ancla en una base institucional colectiva.",
        "This research is situated within the digitalisation of agri-food chains line: the technical subsystem of ADG —immutable traceability, IoT and EUDR compliance— is designed jointly with the associative governance that operates it, demonstrating that digital architecture only produces value retention when anchored in a collective institutional base."),
"UV": ("Esta investigación dialoga con la tradición de economía social y cooperativa del Institut IUDESCOOP: la GDA fundamenta el subsistema social en los principios de autogobierno cooperativo y acción colectiva (Ostrom, 1990), analizando cómo las organizaciones asociativas caficultoras gobiernan democráticamente una infraestructura digital común para capturar valor en origen.",
       "This research engages the social and cooperative economy tradition of the IUDESCOOP Institute: ADG grounds its social subsystem in the principles of cooperative self-governance and collective action (Ostrom, 1990), analysing how associative coffee organisations democratically govern a shared digital infrastructure to capture value at origin."),
"UAM": ("Esta investigación se inscribe en la tradición de economía del desarrollo de la UAM: la GDA modela las condiciones institucionales que permiten a las economías productoras del Sur Global superar el intercambio desigual (Wallerstein, 1974) y revertir el deterioro de los términos de intercambio mediante la retención de valor en origen en cadenas globales.",
        "This research is situated within the development economics tradition of UAM: ADG models the institutional conditions that allow Global South producer economies to overcome unequal exchange (Wallerstein, 1974) and reverse the deterioration of the terms of trade through value retention at origin in global chains."),
"UPC": ("Esta investigación se inscribe en la línea de sostenibilidad y sistemas sociotécnicos de la UPC: la GDA diseña conjuntamente el subsistema técnico (trazabilidad, IoT, registros distribuidos) y el subsistema social que lo gobierna, demostrando —en el sentido sociotécnico de optimización conjunta— que la infraestructura digital solo genera retención de valor cuando se ancla en gobernanza colectiva.",
        "This research is situated within the sustainability and socio-technical systems line of UPC: ADG jointly designs the technical subsystem (traceability, IoT, distributed ledgers) and the social subsystem that governs it, demonstrating —in the socio-technical sense of joint optimisation— that digital infrastructure only generates value retention when anchored in collective governance."),
"Bologna": ("Esta investigación se inscribe en el Topic 4 — Agricultural and Food Economics and Policy del programa (DISTAL, coord. Prof. Diana Di Gioia): la GDA modela empíricamente la distribución del valor en cadenas agroalimentarias globales y las condiciones de política e institucionales bajo las cuales las organizaciones de pequeños productores incrementan su valor capturado en origen.",
            "This research is situated within Topic 4 — Agricultural and Food Economics and Policy of the programme (DISTAL, coord. Prof. Diana Di Gioia): ADG empirically models the distribution of value in global agri-food chains and the policy and institutional conditions under which smallholder organisations increase their value captured at origin."),
"Firenze": ("Esta investigación se inscribe en la gestión sostenible de los recursos agroalimentarios: la GDA integra la gobernanza colectiva y la trazabilidad digital para una gestión territorial sostenible de la cadena del café, alineando el cumplimiento ambiental (EUDR) con la retención de valor en las organizaciones productoras del Sur Global.",
            "This research is situated within the sustainable management of agri-food resources: ADG integrates collective governance and digital traceability for a sustainable territorial management of the coffee chain, aligning environmental compliance (EUDR) with value retention in Global South producer organisations."),
"ZEF": ("Esta investigación se inscribe en el grupo de Economic and Technological Change del BIGS-DR: la GDA aborda el cambio tecnológico e institucional en sistemas alimentarios de países en desarrollo, examinando cómo la gobernanza digital asociativa habilita a las organizaciones caficultoras colombianas (país elegible DAC) para capturar valor en origen y superar las asimetrías de las cadenas globales.",
        "This research is situated within the Economic and Technological Change group of BIGS-DR: ADG addresses technological and institutional change in the food systems of developing countries, examining how associative digital governance enables Colombian coffee organisations (a DAC-eligible country) to capture value at origin and overcome the asymmetries of global chains."),
"Wageningen": ("Esta investigación se inscribe en las tradiciones de Rural Sociology y Knowledge, Technology & Innovation de WUR: la GDA articula la gobernanza de organizaciones de pequeños productores con la innovación sociotécnica, analizando las condiciones bajo las cuales el conocimiento y la tecnología se apropian colectivamente para reposicionar a los caficultores del Sur Global en la cadena global de valor.",
               "This research is situated within the Rural Sociology and Knowledge, Technology & Innovation traditions of WUR: ADG articulates the governance of smallholder organisations with socio-technical innovation, analysing the conditions under which knowledge and technology are collectively appropriated to reposition Global South coffee growers in the global value chain."),
"TUDelft": ("Esta investigación se inscribe en el enfoque de sistemas sociotécnicos y gobernanza multiactor de la facultad TPM: la GDA constituye un diseño institucional para infraestructuras digitales de confianza (registros distribuidos, soberanía de datos), donde la optimización conjunta del subsistema social y técnico determina la distribución del valor en cadenas globales complejas.",
            "This research is situated within the socio-technical systems and multi-actor governance approach of the TPM Faculty: ADG constitutes an institutional design for digital trust infrastructures (distributed ledgers, data sovereignty), where the joint optimisation of the social and technical subsystems determines value distribution in complex global chains."),
"Utrecht": ("Esta investigación se inscribe en la línea de Sustainable Food System Governance (Prof. Hens Runhaar, Copernicus Institute): la GDA aporta un modelo de gobernanza de sistemas alimentarios orientado a transiciones de sostenibilidad, donde la coordinación asociativa y la mediación digital habilitan la captura de valor en origen y el cumplimiento de estándares ambientales globales.",
            "This research is situated within the Sustainable Food System Governance line (Prof. Hens Runhaar, Copernicus Institute): ADG contributes a food-systems governance model oriented towards sustainability transitions, where associative coordination and digital mediation enable value capture at origin and compliance with global environmental standards."),
"Lund": ("Esta investigación se inscribe en la Sustainability Science de LUCSUS: la GDA analiza, desde una perspectiva de sistemas socioecológicos y economía política de las cadenas globales, las condiciones de gobernanza bajo las cuales los territorios productores del Sur Global retienen valor y capacidad de decisión, contribuyendo a la justicia distributiva en la transición sostenible del sistema alimentario.",
         "This research is situated within LUCSUS Sustainability Science: ADG analyses, from a social-ecological systems and global-chain political-economy perspective, the governance conditions under which Global South producer territories retain value and decision-making capacity, contributing to distributive justice in the sustainable transition of the food system."),
"Helsinki": ("Esta investigación se inscribe en la Sustainability Science de HELSUS, en su cruce entre Agricultura y Ciencias Sociales: la GDA aborda la gobernanza de la transición sostenible de los sistemas agroalimentarios, articulando la coordinación asociativa, el cumplimiento ambiental (EUDR) y la captura de valor en origen en territorios del Sur Global.",
             "This research is situated within HELSUS Sustainability Science, at its intersection of Agriculture and Social Sciences: ADG addresses the governance of the sustainable transition of agri-food systems, articulating associative coordination, environmental compliance (EUDR) and value capture at origin in Global South territories."),
"Stockholm": ("Esta investigación dialoga con el enfoque de sistemas socioecológicos del Stockholm Resilience Centre: la GDA examina las condiciones de gobernanza bajo las cuales las organizaciones caficultoras gestionan colectivamente recursos comunes y mantienen su viabilidad frente a la volatilidad de precios y las disrupciones del posconflicto, contribuyendo a la gobernanza adaptativa de cadenas globales.",
              "This research engages the social-ecological systems approach of the Stockholm Resilience Centre: ADG examines the governance conditions under which coffee organisations collectively manage common resources and maintain their viability in the face of price volatility and post-conflict disruptions, contributing to the adaptive governance of global chains."),
"Copenhagen": ("Esta investigación se inscribe en la economía de los recursos y la alimentación del IFRO: la GDA modela cuantitativamente la distribución del valor en la cadena global del café y las condiciones institucionales que permiten a las organizaciones de pequeños productores incrementar su valor capturado en origen frente a estructuras oligopsónicas.",
               "This research is situated within the food and resource economics of IFRO: ADG quantitatively models the distribution of value in the global coffee chain and the institutional conditions that allow smallholder organisations to increase their value captured at origin against oligopsonistic structures."),
"SLU": ("Esta investigación se inscribe en la tradición de desarrollo rural y cadenas agroalimentarias de la SLU: la GDA integra gobernanza asociativa e innovación sociotécnica para reposicionar a las organizaciones caficultoras del Sur Global en la cadena global de valor, vinculando sostenibilidad ambiental y retención de renta territorial.",
        "This research is situated within the rural development and agri-food value chains tradition of SLU: ADG integrates associative governance and socio-technical innovation to reposition Global South coffee organisations in the global value chain, linking environmental sustainability and territorial rent retention."),
"Aarhus": ("Esta investigación se inscribe en la intersección de gestión y ciencias sociales de Aarhus BSS: la GDA constituye un modelo de diseño organizacional e institucional para organizaciones de productores, examinando cómo la gobernanza colectiva mediada digitalmente transforma su posición y su captura de valor en cadenas globales.",
           "This research is situated at the intersection of management and social sciences of Aarhus BSS: ADG constitutes an organisational and institutional design model for producer organisations, examining how digitally mediated collective governance transforms their position and their value capture in global chains."),
"NMBU": ("Esta investigación se inscribe en los estudios de medio ambiente y desarrollo internacional de Noragric: la GDA aborda la justicia distributiva y la gobernanza ambiental en cadenas agroalimentarias del Sur Global, situando a las organizaciones caficultoras de territorios PDET posconflicto como agentes de retención de valor, conocimiento y soberanía de datos en origen.",
         "This research is situated within the international environment and development studies of Noragric: ADG addresses distributive justice and environmental governance in Global South agri-food chains, positioning coffee organisations in post-conflict PDET territories as agents of value, knowledge and data-sovereignty retention at origin."),
}

# folder, encaje_key, uni_name, programa_es, programa_en, is_upm
UNIS = [
 (os.path.join(ACT,"01_UPM_TAPAS"),"UPM","Universidad Politécnica de Madrid","Doctorado en Tecnología Agroambiental para una Agricultura Sostenible (TAPAS)","PhD in Agro-Environmental Technology for Sustainable Agriculture (TAPAS)",True),
 (os.path.join(ACT,"02_Deusto"),"Deusto","Universidad de Deusto","Competitividad Empresarial y Territorial, Innovación y Sostenibilidad (CETIS)","Business and Territorial Competitiveness, Innovation and Sustainability (CETIS)",False),
 (os.path.join(ACT,"03_Loyola"),"Loyola","Universidad Loyola Andalucía","Doctorado en Desarrollo Inclusivo y Sostenible","PhD in Inclusive and Sustainable Development",False),
 (os.path.join(ACT,"04_Mondragon"),"Mondragon","Mondragon Unibertsitatea","Gestión Avanzada de Organizaciones y Economía Social","Advanced Management of Organisations and Social Economy",False),
 (os.path.join(ACT,"05_UAB"),"UAB","Universitat Autònoma de Barcelona","Doctorado (Sociología económica / STS)","PhD (Economic Sociology / STS)",False),
 (os.path.join(ACT,"06_UPV"),"UPV","Universitat Politècnica de València","Doctorado (Cadenas agroalimentarias digitales)","PhD (Digital agri-food chains)",False),
 (os.path.join(ACT,"07_UV_Valencia"),"UV","Universitat de València","Doctorado (IUDESCOOP — Economía Social y Cooperativa)","PhD (IUDESCOOP — Social and Cooperative Economy)",False),
 (os.path.join(ACT,"08_UAM_Madrid"),"UAM","Universidad Autónoma de Madrid","Doctorado en Desarrollo Económico","PhD in Development Economics",False),
 (os.path.join(ACT,"09_UPC_Cataluna"),"UPC","Universitat Politècnica de Catalunya","Doctorado (Sostenibilidad / Sistemas sociotécnicos)","PhD (Sustainability / Socio-technical systems)",False),
 (os.path.join(INT,"07_Bologna"),"Bologna","Università di Bologna","PhD in Agricultural, Environmental and Food Science and Technology (DISTAL)","PhD in Agricultural, Environmental and Food Science and Technology (DISTAL)",False),
 (os.path.join(INT,"08_Firenze"),"Firenze","Università degli Studi di Firenze","PhD in Gestione Sostenibile delle Risorse Agrarie, Forestali e Alimentari","PhD in Sustainable Management of Agricultural, Forestry and Food Resources",False),
 (os.path.join(INT,"09_ZEF_Bonn"),"ZEF","ZEF — University of Bonn","BIGS-DR Doctoral Programme (Development Research)","BIGS-DR Doctoral Programme (Development Research)",False),
 (os.path.join(INT,"10_Wageningen"),"Wageningen","Wageningen University & Research","PhD — Rural Sociology / Knowledge, Technology & Innovation","PhD — Rural Sociology / Knowledge, Technology & Innovation",False),
 (os.path.join(INT,"11_TU_Delft"),"TUDelft","Delft University of Technology","PhD — Technology, Policy & Management (TPM)","PhD — Technology, Policy & Management (TPM)",False),
 (os.path.join(INT,"12_Utrecht"),"Utrecht","Utrecht University","PhD — Copernicus Institute (Sustainable Food System Governance)","PhD — Copernicus Institute (Sustainable Food System Governance)",False),
 (os.path.join(INT,"13_Lund"),"Lund","Lund University","PhD — LUCSUS (Sustainability Science)","PhD — LUCSUS (Sustainability Science)",False),
 (os.path.join(INT,"14_Helsinki_HELSUS"),"Helsinki","University of Helsinki","PhD — HELSUS (Sustainability Science)","PhD — HELSUS (Sustainability Science)",False),
 (os.path.join(INT,"15_Stockholm_Resilience"),"Stockholm","Stockholm University","PhD — Stockholm Resilience Centre (Sustainability Science)","PhD — Stockholm Resilience Centre (Sustainability Science)",False),
 (os.path.join(INT,"16_Copenhagen_IFRO"),"Copenhagen","University of Copenhagen","PhD — Food and Resource Economics (IFRO)","PhD — Food and Resource Economics (IFRO)",False),
 (os.path.join(INT,"17_SLU_Suecia"),"SLU","Swedish University of Agricultural Sciences","PhD — Rural Development / Agri-food value chains","PhD — Rural Development / Agri-food value chains",False),
 (os.path.join(INT,"18_Aarhus_BSS"),"Aarhus","Aarhus University","PhD — Business and Social Sciences (BSS)","PhD — Business and Social Sciences (BSS)",False),
 (os.path.join(INT,"19_NMBU_Noragric"),"NMBU","Norwegian University of Life Sciences","PhD — Noragric (International Environment and Development Studies)","PhD — Noragric (International Environment and Development Studies)",False),
]

def add_body(doc, text):
    p = doc.add_paragraph(text)
    p.paragraph_format.space_after = Pt(8)
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    return p

def build(uni, lang):
    path, key, uname, prog_es, prog_en, is_upm = uni
    es = (lang == "ES")
    doc = Document()
    # Encabezado
    h = doc.add_paragraph()
    r = h.add_run("PROPUESTA DE INVESTIGACIÓN" if es else "RESEARCH PROPOSAL")
    r.bold = True; r.font.size = Pt(14)
    h.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.add_run(uname + "\n").bold = True
    sub.add_run((prog_es if es else prog_en) + "\n")
    sub.add_run(("Proponente: " if es else "Applicant: ") + AUTOR)
    doc.add_paragraph()
    # 1
    doc.add_heading("1. Título provisional y palabras clave" if es else "1. Working title and keywords", level=1)
    p = doc.add_paragraph(); p.add_run(("Título: " if es else "Title: ")).bold = True
    p.add_run(TITULO_ES if es else TITULO_EN)
    p = doc.add_paragraph(); p.add_run(("Pregunta de investigación: " if es else "Research question: ")).bold = True
    p.add_run(PREGUNTA_ES if es else PREGUNTA_EN)
    p = doc.add_paragraph(); p.add_run(("Palabras clave: " if es else "Keywords: ")).bold = True
    p.add_run(KW_ES if es else KW_EN)
    # 2
    doc.add_heading("2. Planteamiento del problema y justificación" if es else "2. Problem statement and justification", level=1)
    for t in (SEC2_ES if es else SEC2_EN): add_body(doc, t)
    # 3 (núcleo + encaje)
    doc.add_heading("3. Estado del arte y encuadre teórico" if es else "3. State of the art and theoretical framework", level=1)
    for t in (SEC3_ES if es else SEC3_EN): add_body(doc, t)
    add_body(doc, ENC[key][0 if es else 1])
    # 4
    doc.add_heading("4. Orientación metodológica" if es else "4. Methodological approach", level=1)
    for t in (SEC4_ES if es else SEC4_EN): add_body(doc, t)
    # 5
    doc.add_heading("5. Referencias" if es else "5. References", level=1)
    refs = list(REFS_CORE) + (REFS_UPM_EXTRA if is_upm else [])
    refs.sort(key=lambda s: s.lower())
    for ref in refs:
        rp = doc.add_paragraph(ref)
        rp.paragraph_format.left_indent = Pt(18)
        rp.paragraph_format.first_line_indent = Pt(-18)
        rp.paragraph_format.space_after = Pt(4)
    fn = "Propuesta_GDA_ES.docx" if es else "Research_Proposal_GDA_EN.docx"
    out = os.path.join(path, fn)
    doc.save(out)
    return out

count = 0
for uni in UNIS:
    for lang in ("ES", "EN"):
        if not os.path.isdir(uni[0]):
            print("FALTA CARPETA:", uni[0]); continue
        out = build(uni, lang)
        count += 1
        print("OK", os.path.relpath(out, ROOT))
print("\nTOTAL DOCUMENTOS:", count)
